service: pexels-express-api
frameworkVersion: "3"
app: pexels-express-api

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    API_KEY: ${param:API_KEY, env:API_KEY, ""}

functions:
  api:
    handler: index.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: "{proxy+}"
          cors: true

  search:
    handler: index.handler
    events:
      - http:
          method: GET
          path: "/search/{proxy+}"
          cors: true

  curated:
    handler: index.handler
    events:
      - http:
          method: GET
          path: "/curated/{proxy+}"
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 9000
    autoReload: true
